database:
  restart: always
  image: postgres:latest
  volumes:
    - pgdata:/var/lib/postgresql/data/
  environment:
    POSTGRES_USER: django
mastermind:
  build: .
  environment:
    - DJANGO_SETTINGS_MODULE: mastermind.settings.prod
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/django
  ports:
    - "8000:8000"
  links:
    - database
  environment:
    DATABASE_NAME: django
    DATABSE_USER: django
    DATABASE_PASSWORD: django
    DATABASE_SERVICE_HOST: database
