# Generated by Django 2.2.1 on 2019-05-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[(0, 'finished'), (1, 'ongoing')], max_length=20)),
                ('colors', models.ManyToManyField(to='game.Color')),
            ],
        ),
    ]
