# Generated by Django 2.2.1 on 2019-05-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[(0, 'finished'), (1, 'ongoing')], max_length=20)),
                ('c1', models.CharField(max_length=10)),
                ('c2', models.CharField(max_length=10)),
                ('c3', models.CharField(max_length=10)),
                ('c4', models.CharField(max_length=10)),
            ],
        ),
    ]
