# Generated by Django 2.2.1 on 2019-05-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='colors',
            new_name='color_ids',
        ),
    ]
