# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190515_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c1', models.CharField(max_length=10)),
                ('c2', models.CharField(max_length=10)),
                ('c3', models.CharField(max_length=10)),
                ('c4', models.CharField(max_length=10)),
                ('black_pegs', models.IntegerField()),
                ('white_pegs', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='guess',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
    ]
