# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190516_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.IntegerField(choices=[(0, 'finished'), (1, 'ongoing')]),
        ),
    ]
